JSONObfuscator.duplicateProperty=Duplicate %s property/valueType combination: %s, %s
JSONObfuscator.duplicatePropertyPathMatcher=Duplicate propertyPath matcher/valueType combination: %s, %s
JSONObfuscator.malformedJSON.warning=Could not fully obfuscate text
JSONObfuscator.malformedJSON.text=<obfuscation aborted due to malformed JSON>
JSONObfuscator.unexpectedEvent=Unexpected event: %s
